### ISSUE TITLE
Add releases to test

### ISSUE THREAD

**Issue by andrasfuchs** [maxneaga/open_dash_cam_android#12]
I would be glad to join the testers, but I'm not an Android expert, so it would be nice to have some releases/apk packages and a small tutorial about installing it on our phones.

**Comment by maxneaga** [comment]
Thank you for sharing the idea and for willingness to join the testers, Andras! Android allows to have alpha and beta releases for testers, this way you could test by simply downloading an alpha or beta version from the Google Play store. Does that solution sound good to you?

**Comment by andrasfuchs** [comment]
Thanks @maxneaga , I've just installed it from the Play Store, so far so good! 👍
