### ISSUE TITLE
Only keep x minutes of video

### ISSUE THREAD

**Issue by andrasfuchs** [maxneaga/open_dash_cam_android#16]
It would be useful if we didn't need to delete video files one-by-one. The majority of the files will be not used, so they should be deleted automatically, if they are not starred.

All files are 1 minute-long now, so if let's say there are more then 120 not-starred files in the folder, the oldest ones should be deleted automatically.

**Comment by maxneaga** [comment]
@andrasfuchs 
As I'm sure you have already noticed, the videos are being automatically rotated (older ones get deleted when the new ones are recorded). I am happy you opened this issue, because it tells me we need to make it more clear to the users that that is what is happening.
